spring:
 application:
  name: puertaEntrada

 cloud:
  loadbalancer:
   enabled: true

  gateway:
   server:
    webflux:
     routes:
      - id: usuario
        uri: lb://usuario
        predicates:
         - Path=/api/users/**
        filters:
         - StripPrefix=2

      - id: persona
        uri: lb://persona
        predicates:
         - Path=/api/personas/**
        filters:
         - StripPrefix=2

      - id: publicacion
        uri: lb://publicacion
        predicates:
         - Path=/api/publicaciones/**
        filters:
         - StripPrefix=2

server:
 port: 8090

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka